### PR TITLE
Update the env yaml

### LINKED ISSUE #6: Create env yaml
I created a conda environment yaml file for every to start the project with.

### PR DESCRIPTION
**Pull request by 786213750**

### CODE REVIEW

**Review by s-voon — APPROVED** [review]
Looks good to me! Just wondering if we need to specify the specific version. Let me know what you think

**Comment by 786213750** [comment]
> Looks good to me! Just wondering if we need to specify the specific version. Let me know what you think

Yea, I was thinking about that. This yaml is similar to env in 574 which are without version so I keep it that way.

**Comment by MoNorouzi23** [comment]
Thanks Thomas, I think we need to add version of each dependencies as well and also we need some other packages like:
altair=5.1.2
vegafusion=1.4.3
folium=0.15.0
seaborn=0.13.0

**Review by s-voon — APPROVED** [review]

**Comment by 786213750** [comment]
> Thanks Thomas, I think we need to add version of each dependencies as well and also we need some other packages like: altair=5.1.2 vegafusion=1.4.3 folium=0.15.0 seaborn=0.13.0

Thanks, I just updated.

**Comment by MoNorouzi23** [comment]
thanks; good job!

**Review by WaleedMahmood1 — APPROVED** [review]
I think these are good libraries for our project. They should cover most functionalities that we might want to add in out dashboard.

**Pull request merged**
